<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Kelurahan;

class KelurahanSeeder extends Seeder
{
    public function run()
    {
        $kelurahan = [
            'Gempol Sari',
            'Cigondewah Kaler',
            'Cigondewah Kidul',
            'Cigondewah Rahayu',
            'Caringin',
            'Warung Muncang',
            'Cibuntu',
            'Cijerah',
            'Margasuka',
            'Cirangrang',
            'Margahayu Utara',
            'Babakan Ciparay',
            'Babakan',
            'Sukahaji',
            'Kopo',
            'Suka Asih',
            'Babakan Asih',
            'Babakan Tarogong',
            'Jamika',
            'Cibaduyut Kidul',
            'Cibaduyut Wetan',
            'Mekar Wangi',
            'Cibaduyut',
            'Kebon Lega',
            'Situsaeur',
            'Karasak',
            'Pelindung Hewan',
            'Nyengseret',
            'Panju0n',
            'Cibadak',
            'Karang Anyar',
            'Ciseureuh',
            'Pasirluyu',
            'Ancol',
            'Cigereleng',
            'Ciateul',
            'Pungkur',
            'Balong Gede',
            'Cijagra',
            'Turangga',
            'Lingkar Selatan',
            'Malabar',
            'Burangrang',
            'Cikawao',
            'Paledang',
            'Wates',
            'Mengger',
            'Batununggal',
            'Kujangsari',
            'Cijaura',
            'Margasari',
            'Sekejati',
            'Jati Sari',
            'Derwati',
            'Cipamokolan',
            'Manjahlega',
            'Mekarjaya',
            'Rancabolang',
            'Rancanumpang',
            'Cisaranten Kidul',
            'Cimincrang',
            'Pasir Biru',
            'Cipadung',
            'Palasari',
            'Cisurupan',
            'Mekar Mulya',
            'Cipadung Kidul',
            'Cipadung Wetan',
            'Cipadung Kulon',
            'Pasanggrahan',
            'Pasirjati',
            'Pasir Wangi',
            'Cigending',
            'Pasir Endah',
            'Cisaranten Wetan',
            'Babakan Penghulu',
            'Pakemitan',
            'Sukamulya',
            'Cisaranten Kulon',
            'Cisaranten Bina Harapan',
            'Sukamiskin',
            'Cisaranten Endah',
            'Antapani Kidul',
            'Antapani Tengah',
            'Antapani Wetan',
            'Antapani Kulon',
            'Jatihandap',
            'Karang Pamulang',
            'Sindang Jaya',
            'Pasir Impun',
            'Kebon Kangkung',
            'Sukapura',
            'Kebun Jayanti',
            'Babakan Sari',
            'Babakan Surabaya',
            'Cicaheum',
            'Gumuruh',
            'Binong',
            'Kebon Gedang',
            'Maleer',
            'Cibangkong',
            'Samoja',
            'Kacapiring',
            'Kebon Waru',
            'Braga',
            'Kebon Pisang',
            'Merdeka',
            'Babakan Ciamis',
            'Campaka',
            'Maleber',
            'Garuda',
            'Dungus Cariang',
            'Ciroyom',
            'Kebon Jeruk',
            'Arjuna',
            'Pasirkaliki',
            'Pamoyanan',
            'Pajajaran',
            'Husen Sastranegara',
            'Sukaraja',
            'Taman Sari',
            'Citarum',
            'Cihapit',
            'Sukamaju',
            'Cicadas',
            'Cikutra',
            'Padasuka',
            'Pasirlayung',
            'Sukapada',
            'Cihaurgeulis',
            'Sukaluyu',
            'Neglasari',
            'Cigadung',
            'Cipaganti',
            'Lebak Siliwangi',
            'Lebak Gede',
            'Sadang Serang',
            'Sekeloa',
            'Dago',
            'Sukawarna',
            'Sukagalih',
            'Sukabungah',
            'Cipedes',
            'Pasteur',
            'Sarijadi',
            'Sukarasa',
            'Gegerkalong',
            'Isola',
            'Hegarmanah',
            'Ciumbuleuit',
            'Ledeng'
        ];

        foreach ($kelurahan as $nama_kelurahan) {
            Kelurahan::create(['nama_kelurahan' => $nama_kelurahan]);
        }
    }
}
